var R=[
  {n:"A Spurcacciun-a",a:"Via Famagosta 24, Savona, Liguria",pl:4,pr:"€€€€ · ~95€",cu:"Alta Cucina di Mare",tg:"pesce",ws:"https://www.google.com/search?q=A%20Spurcacciun-a%20ristorante",st:"Nella guida Michelin a Savona. Chef Simone Perata. Vista sul mare dalla zona giardino. Cucina di pesce contemporanea con ingredienti del Tirreno: i rossetti con carciofi e curry verde sono il piatto firma.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["I rossetti con carciofi alla griglia e salsa al curry verde: il piatto che ha fatto conoscere Savona al mondo gourmet.","Il giardino affacciato sul mare in estate e una delle terrazze piu belle della Liguria.","Simone Perata usa il pesce povero ligure con una tecnica che lo eleva all alta cucina."]},
  {n:"Agriturismo Su Gologone",a:"Loc. Su Gologone, Oliena, Sardegna",pl:3,pr:"€€€ · ~60€",cu:"Sarda Tradizionale",tg:"italiana",ws:"https://www.google.com/search?q=Agriturismo%20Su%20Gologone%20ristorante",st:"Agriturismo storico nel cuore della Barbagia vicino alla sorgente carsica di Su Gologone. Cucina sarda autentica: maialetto arrosto, culurgiones, porceddu. A breve distanza dal mare del Golfo di Orosei.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Su Gologone e uno dei luoghi piu suggestivi della Sardegna: la sorgente, la Barbagia, la tradizione.","Il maialetto arrosto su Gologone e uno dei piu buoni d Italia: cottura lenta nel forno a legna.","A due passi dal mare del Golfo di Orosei, il piu bello d Italia: terra e mare della Sardegna."]},
  {n:"Al Gallo",a:"Via della Repubblica 5, Ravenna, Emilia Romagna",pl:3,pr:"€€€ · ~55€",cu:"Ravennate Tradizionale",tg:"pesce",ws:"https://www.google.com/search?q=Al%20Gallo%20ristorante",st:"Ristorante storico di Ravenna vicino al mare di Marina di Ravenna. Cucina ravennate di tradizione: anguilla marinata, seppie nere, brodo di pesce. Cantina con grande selezione di Sangiovese.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["L anguilla marinata di Ravenna e un patrimonio gastronomico quasi scomparso: qui si trova ancora.","La cucina ravennate di mare e diversa da quella riminese: meno fritta, piu stufata.","La cantina con il Sangiovese di Romagna e una delle ragioni per venire a Ravenna."]},
  {n:"Al Volo Focacceria Moderna",a:"Via Vittorio Emanuele 102, Palermo, Sicilia",pl:1,pr:"€ · ~12€",cu:"Street Food Palermitano",tg:"italiana",ws:"https://www.google.com/search?q=Al%20Volo%20Focacceria%20Moderna%20ristorante",st:"La focacceria piu famosa di Palermo. Sfincione palermitano, pane ca meusa, arancine di riso. Lo street food siciliano nella sua forma piu autentica e popolare.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:14,l:"14/20"},rv:["Lo sfincione palermitano e il pane ca meusa sono i piatti che si mangiano solo a Palermo.","Il mercato di Ballarò attorno alla focacceria e lo street food piu autentico della Sicilia.","I prezzi da pochi euro per una qualita che non si trova altrove: il miracolo dello street food palermitano."]},
  {n:"Andreina",a:"Via Buffolareccia 14, Loreto, Marche",pl:4,pr:"€€€€ · ~85€",cu:"Alta Cucina Marchigiana",tg:"italiana",ws:"https://www.google.com/search?q=Andreina%20ristorante",st:"Una stella Michelin a Loreto. Chef Errico Recanati. Cucina marchigiana contemporanea con brace come elemento centrale. Il fuoco come tecnica principale per esaltare gli ingredienti di terra e mare.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["La brace e la tecnica principale di Recanati: ogni ingrediente diventa piu intenso e profondo.","Una stella Michelin per una cucina marchigiana di grande personalita e identita.","Il pollo ruspante alla brace con le erbe e il piatto che racconta questa cucina."]},
  {n:"Babette Albenga",a:"Via Michelangelo Buonarroti 17, Albenga, Liguria",pl:3,pr:"€€€ · ~65€",cu:"Ligure Gourmet",tg:"pesce",ws:"https://www.google.com/search?q=Babette%20Albenga%20ristorante",st:"Ristorante fronte spiaggia davanti all Isola Gallinara, area marina protetta. Cucina ligure gourmet di mare con ingredienti di altissima qualita. Cena letteralmente in riva al mare.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Fronte spiaggia con vista sull Isola Gallinara, area marina protetta: location unica.","La cucina ligure gourmet di mare qui trova un indirizzo di grande qualita.","Cenare letteralmente in riva al mare con l Isola Gallinara sullo sfondo: un sogno."]},
  {n:"Bontà delle Marche",a:"Lungomare da Vinci 2, San Benedetto del Tronto, Marche",pl:2,pr:"€€ · ~38€",cu:"Pesce Adriatico",tg:"pesce",ws:"https://www.google.com/search?q=Bont%C3%A0%20delle%20Marche%20ristorante",st:"Trattoria di pesce sul lungomare di San Benedetto del Tronto. Cucina marchigiana di mare della tradizione: la guitola fritta, le mazzancolle e il brodetto alla sanbenedettese con peperoni verdi.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Il brodetto alla sanbenedettese con i peperoni verdi e unico in Italia: diverso da tutti gli altri.","La guitola (razze) fritta e un piatto che si trova solo qui: la cucina di mare delle Marche e originale.","San Benedetto del Tronto e la capitale del pesce azzurro adriatico: qui lo si cucina al meglio."]},
  {n:"Buca di Sant'Antonio",a:"Via della Cervia 3, Lucca, Toscana",pl:2,pr:"€€ · ~45€",cu:"Toscana Tradizionale",tg:"italiana",ws:"https://www.google.com/search?q=Buca%20di%20Sant'Antonio%20ristorante",st:"La trattoria storica di Lucca dal 1782, a pochi chilometri dal mare della Versilia. Cucina toscana della tradizione: fagioli all uccelletto, ribollita, pappardelle al cinghiale. Vicino alla costa.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Dal 1782: la trattoria piu antica della Toscana e uno dei patrimoni gastronomici della regione.","La cucina toscana autentica qui non ha ceduto alle mode: tutto e come deve essere.","A pochi chilometri dalla Versilia: la tappa perfetta prima o dopo il mare."]},
  {n:"Calajanara",a:"Via Calajanara, Ponza, Lazio",pl:4,pr:"€€€€ · ~80€",cu:"Pesce Pontino",tg:"pesce",ws:"https://www.google.com/search?q=Calajanara%20ristorante",st:"Ristorante sull isola di Ponza raggiungibile solo via barca. Cucina pontina di mare: aragoste di Ponza, polpi, alici e pesce pane. Una delle esperienze marine piu esclusive del Lazio.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Raggiungibile solo via barca: l esclusivita inizia prima ancora di sedersi a tavola.","Le aragoste di Ponza sono tra le piu pregiate del Mediterraneo: qui le cucinano alla perfezione.","L isola di Ponza e uno dei luoghi piu belli d Italia: Calajanara ne e l indirizzo gastronomico."]},
  {n:"Capofaro Locanda e Malvasia",a:"Via Faro 3, Malfa, Sicilia",pl:4,pr:"€€€€ · ~90€",cu:"Eoliana",tg:"pesce",ws:"https://www.google.com/search?q=Capofaro%20Locanda%20e%20Malvasia%20ristorante",st:"Ristorante nell hotel boutique nel vigneto di Malvasia a Salina. Vista sullo stretto tra Salina e Stromboli. Cucina eoliana: capperi di Salina, Malvasia delle Lipari, pesce dello stretto.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Il vigneto di Malvasia a Salina con Stromboli fumante sullo sfondo: la vista piu vulcanica d Italia.","I capperi di Salina e la Malvasia delle Lipari sono ingredienti unici al mondo.","Un ristorante che racconta le Isole Eolie come nessun altro: identita assoluta."]},
  {n:"Caracol",a:"Via Faro 1, Bacoli, Campania",pl:5,pr:"€€€€€ · ~130€",cu:"Alta Cucina di Mare",tg:"pesce",ws:"https://www.google.com/search?q=Caracol%20ristorante",st:"Una stella Michelin nei Campi Flegrei a Bacoli. Chef Stefano Mazzone. Cucina di mare tra i crateri vulcanici con panorama sul golfo di Pozzuoli. Il pesce del golfo di Pozzuoli e tra i piu pregiati d Italia.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["Tra i crateri vulcanici dei Campi Flegrei: una location geologicamente impossibile da dimenticare.","Il pesce del golfo di Pozzuoli e tra i piu freschi e pregiati d Italia.","Una stella Michelin in uno dei posti piu suggestivi della Campania."]},
  {n:"Carmelo's",a:"Via Stazione 23, Catania, Sicilia",pl:2,pr:"€€ · ~38€",cu:"Catanese di Mare",tg:"pesce",ws:"https://www.google.com/search?q=Carmelo's%20ristorante",st:"Ristorante di pesce storico di Catania ai piedi dell Etna. Cucina catanese di mare: pasta alla norma con il pesce, spiedini di pesce spada, sarde a beccafico. Il Mediterraneo davanti all Etna.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["L Etna e il Mediterraneo in un unico ristorante: terra e mare della Sicilia insieme.","La pasta alla norma con il pesce e un invenzione catanese che non si trova altrove.","Le sarde a beccafico di Catania sono diverse da quelle palermitane: ogni zona ha la sua versione."]},
  {n:"Claudio",a:"Via XXV Aprile 37, Bergeggi, Liguria",pl:5,pr:"€€€€€ · ~120€",cu:"Alta Cucina di Mare",tg:"pesce",ws:"https://www.google.com/search?q=Claudio%20ristorante",st:"Una stella Michelin a Bergeggi. Chef Claudio Pasquarelli. Vista sull Isolotto di Bergeggi, riserva naturale protetta. Cucina ligure d autore con il migliore pescato della riviera di Ponente.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["La vista sull Isolotto di Bergeggi e sulla riserva naturale e tra le piu belle della Liguria.","Una stella Michelin per una cucina di pesce che racconta la riviera di Ponente con grande rispetto.","Il pescato della riviera di Ponente e tra i meno noti e piu pregiati d Italia: Claudio lo valorizza."]},
  {n:"Cracco Portofino",a:"Calata Marconi 12, Portofino, Liguria",pl:5,pr:"€€€€€ · ~180€",cu:"Alta Cucina di Mare",tg:"pesce",ws:"https://www.google.com/search?q=Cracco%20Portofino%20ristorante",st:"Nuova stella Michelin 2026. Chef Mattia Pecis (premio Giovane Chef dell Anno). Carlo Cracco sbarca a Portofino con una cucina di mare di altissimo livello. Vista sul porto piu fotografato d Italia.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["La nuova stella piu celebrata del 2026: Mattia Pecis porta una visione personalissima sul mare ligure.","Il porto di Portofino come sfondo: difficile immaginare una location piu iconica d Italia.","Carlo Cracco sceglie Portofino per il suo ristorante di pesce: scelta azzeccata."]},
  {n:"Da Caino",a:"Via della Chiesa 4, Montemerano, Toscana",pl:5,pr:"€€€€€ · ~140€",cu:"Alta Cucina Maremmana",tg:"italiana",ws:"https://www.google.com/search?q=Da%20Caino%20ristorante",st:"Una stella Michelin nella Maremma. Chef Valeria Piccini. Cucina maremmana di altissimo livello: cinghiale, piccione, anguilla e prodotti del territorio lavorati con tecnica sopraffina.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:18,l:"18/20"},rv:["Valeria Piccini e una delle chef piu importanti d Italia: cucina maremmana di altissima classe.","La Maremma nel piatto: cinghiale, anguilla del lago di Burano, funghi e erbe selvatiche.","Uno dei ristoranti piu importanti della Toscana, a torto meno conosciuto di quelli urbani."]},
  {n:"Da Felice",a:"Lungomare Vittorio Veneto 2, Chiavari, Liguria",pl:2,pr:"€€ · ~40€",cu:"Ligure Tradizionale",tg:"pesce",ws:"https://www.google.com/search?q=Da%20Felice%20ristorante",st:"Nella guida Michelin a Chiavari sul Lungomare. Cucina ligure di mare autentica: brandacujun, calamari sulla ciappa, preboggion. Dehors estivo a due passi dalle onde.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:14,l:"14/20"},rv:["Il brandacujun e i calamari sulla pietra ollare: la cucina ligure di mare nella sua versione piu autentica.","Sul Lungomare di Chiavari con dehors estivo: una delle terrazze sul mare piu piacevoli della Liguria.","Un ristorante familiare dove il tempo rallenta e la cucina ligure diventa protagonista."]},
  {n:"Da Lucio",a:"Via Gambalunga 32, Rimini, Emilia Romagna",pl:4,pr:"€€€€ · ~100€",cu:"Alta Cucina Adriatica",tg:"pesce",ws:"https://www.google.com/search?q=Da%20Lucio%20ristorante",st:"Nuova stella Michelin 2026 e premio Menu Degustazione Gambero Rosso. Chef Lucio Pompili. Cucina adriatica d autore a Rimini. Il pesce dell Adriatico elevato a linguaggio gastronomico d autore.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["Nuova stella Michelin 2026 e miglior menu degustazione Gambero Rosso: doppio riconoscimento meritato.","Il pesce dell Adriatico qui parla un linguaggio gastronomico di grande profondita.","Rimini non e solo spiagge: Da Lucio la mette sul mappamondo della grande cucina."]},
  {n:"Da Romolo al Porto",a:"Via Faro 11, Fiumicino, Lazio",pl:2,pr:"€€ · ~40€",cu:"Pesce Laziale",tg:"pesce",ws:"https://www.google.com/search?q=Da%20Romolo%20al%20Porto%20ristorante",st:"Trattoria storica di Fiumicino sul porto canale. Cucina laziale di mare della tradizione: spaghetti alle vongole veraci, branzino al sale, frittura di paranza. Il pesce arriva dai pescherecci del porto ogni mattina.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Il porto canale di Fiumicino e il piu importante del Lazio: il pesce arriva freschissimo.","Gli spaghetti alle vongole veraci sono quelli della tradizione laziale: profumati e abbondanti.","Una trattoria autentica frequentata dai pescatori: la garanzia di qualita piu semplice."]},
  {n:"Dal Corsaro",a:"Viale Regina Margherita 28, Cagliari, Sardegna",pl:5,pr:"€€€€€ · ~130€",cu:"Alta Cucina Sarda",tg:"italiana",ws:"https://www.google.com/search?q=Dal%20Corsaro%20ristorante",st:"Una stella Michelin a Cagliari. Chef Stefano Deidda. La cucina sarda piu importante della Capitale: bottarga di Cabras, arselle della laguna di Nora, crostacei del Tirreno.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["La bottarga di Cabras di Dal Corsaro e quella autentica: il caviale del Mediterraneo.","Stefano Deidda porta la cucina sarda a livelli di alta cucina internazionale senza tradirne le radici.","Una stella Michelin a Cagliari per il ristorante che meglio racconta la Sardegna gastronomica."]},
  {n:"Dalla Gioconda",a:"Via della Vittoria 133, Gabicce Mare, Emilia Romagna",pl:5,pr:"€€€€€ · ~150€",cu:"Alta Cucina Adriatica",tg:"pesce",ws:"https://www.google.com/search?q=Dalla%20Gioconda%20ristorante",st:"Due stelle Michelin e Tre Forchette Gambero Rosso a Gabicce Mare. Chef Agostino Iacobucci. Una delle tavole piu importanti dell Adriatico: cucina di mare d autore con ingredienti dell Adriatico di eccellenza.",mi:{s:2,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:18,l:"18/20"},rv:["Due stelle Michelin a Gabicce Mare: uno dei ristoranti piu importanti dell Adriatico.","Agostino Iacobucci costruisce piatti di grande profondita e ricerca con ingredienti adriatici.","La piadina gourmet con ingredienti di eccellenza e il piatto che simboleggia questa cucina."]},
  {n:"Don Alfonso 1890",a:"Corso Sant'Agata 11, Sant'Agata sui Due Golfi, Campania",pl:5,pr:"€€€€€ · ~180€",cu:"Alta Cucina Campana",tg:"italiana",ws:"https://www.google.com/search?q=Don%20Alfonso%201890%20ristorante",st:"Una stella Michelin e Tre Forchette Gambero Rosso a Sant Agata sui Due Golfi. Chef Alfonso Iaccarino. La cucina campana piu storica e classica: orto proprio, agrumi della costiera e panorama sui due golfi.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:18,l:"18/20"},rv:["Alfonso Iaccarino ha inventato l alta cucina campana: tutto quello che e venuto dopo e debitore a lui.","L orto proprio e il filo conduttore: ingredienti coltivati a pochi metri dalla cucina.","La vista sui due golfi di Napoli e Salerno e probabilmente la piu bella d Italia."]},
  {n:"Emilio",a:"Via dei Cavalleggeri 3, Castagneto Carducci, Toscana",pl:3,pr:"€€€ · ~65€",cu:"Pesce Toscano",tg:"pesce",ws:"https://www.google.com/search?q=Emilio%20ristorante",st:"Ristorante di pesce storico in Costa degli Etruschi. Cucina toscana di mare autentica: il cacciucco, il fritto misto e il branzino vengono da pescatori conosciuti personalmente.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["La Costa degli Etruschi ha nel pesce fresco il suo tesoro: Emilio lo valorizza da decenni.","Il cacciucco e il fritto misto sono eseguiti con il pescato del giorno da pescatori di fiducia.","Un ristorante che resiste ai trend: cucina toscana di mare autentica e senza fronzoli."]},
  {n:"Emilio s Ballatoio",a:"Via Gramsci 16, Portonovo, Marche",pl:4,pr:"€€€€ · ~90€",cu:"Pesce Adriatico",tg:"pesce",ws:"https://www.google.com/search?q=Emilio%20s%20Ballatoio%20ristorante",st:"Ristorante nella baia di Portonovo, la piu bella delle Marche. Cucina di mare marchigiana con moscioli (cozze selvatiche) di Portonovo, il prodotto piu pregiato del Conero.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["La baia di Portonovo e la piu bella delle Marche e il ristorante vi si affaccia direttamente.","I moscioli selvatici di Portonovo sono il prodotto gastronomico piu pregiato del Conero.","Una cucina che racconta la baia e il mare con semplicita e grande materia prima."]},
  {n:"Felix Lo Basso",a:"Via Vittorio Veneto 1, Trani, Puglia",pl:5,pr:"€€€€€ · ~130€",cu:"Alta Cucina Pugliese",tg:"pesce",ws:"https://www.google.com/search?q=Felix%20Lo%20Basso%20ristorante",st:"Una stella Michelin a Trani nel porto piu bello della Puglia. Chef Felix Lo Basso. Cucina pugliese d autore: ricci, ostriche e crudi dell Adriatico davanti alla cattedrale romanica di Trani.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:17,l:"17/20"},rv:["Il porto di Trani con la cattedrale romanica e lo sfondo piu bello della Puglia.","Felix Lo Basso porta la cucina pugliese a un livello di raffinatezza insolito per la regione.","I ricci di mare e le ostriche dell Adriatico davanti al porto: un abbinamento di bellezza assoluta."]},
  {n:"Gabbiano 3.0",a:"Lungomare dell'Etrusco 1, Marina di Grosseto, Toscana",pl:5,pr:"€€€€€ · ~130€",cu:"Alta Cucina di Mare",tg:"pesce",ws:"https://www.google.com/search?q=Gabbiano%203.0%20ristorante",st:"Una stella Michelin a Marina di Grosseto. Chef Fabrizio Cingolani. Cucina di mare toscana d autore direttamente sulla spiaggia della Maremma. Sunset dinner unico.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["Una stella Michelin direttamente sulla spiaggia della Maremma: la cucina piu bella dove cenare.","Il tramonto sulla spiaggia di Marina di Grosseto durante la cena e indimenticabile.","Fabrizio Cingolani usa il pescato della Maremma con tecnica e rispetto assoluti."]},
  {n:"Gambero Rosso",a:"Corso Garibaldi 82, Pizzo Calabro, Calabria",pl:2,pr:"€€ · ~38€",cu:"Calabrese di Mare",tg:"pesce",ws:"https://www.google.com/search?q=Gambero%20Rosso%20ristorante",st:"Ristorante di pesce nel centro di Pizzo Calabro, famosa per il tartufo di cioccolato. Cucina calabrese di mare della tradizione: pesce spada, tonno, alici e frittura dello Ionio.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Pizzo Calabro e famosa per il tartufo al cioccolato ma il pesce e ugualmente straordinario.","Il pesce spada e il tonno dello Ionio sono i prodotti piu pregiati di queste acque.","Un ristorante di pesce autentico in uno dei borghi piu belli della Calabria tirrenica."]},
  {n:"Gianantonio e i suoi Fratelli",a:"Lungomare Nazario Sauro 12, Gallipoli, Puglia",pl:2,pr:"€€ · ~40€",cu:"Salentina di Mare",tg:"pesce",ws:"https://www.google.com/search?q=Gianantonio%20e%20i%20suoi%20Fratelli%20ristorante",st:"Ristorante di pesce storico sul lungomare di Gallipoli. Cucina salentina di mare della tradizione: polpo a pignata, purpu alla pignata, alici fritte. Il pesce dello Ionio e il protagonista.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Gallipoli e la citta piu bella del Salento: il lungomare ha questo ristorante come punto di riferimento.","Il polpo a pignata e la ricetta salentina piu autentica: cottura lenta nella terracotta.","Il pesce dello Ionio e diverso dall Adriatico: piu delicato e aromatico."]},
  {n:"Grotta Palazzese",a:"Via Narciso 59, Polignano a Mare, Puglia",pl:4,pr:"€€€€ · ~100€",cu:"Pugliese di Mare",tg:"pesce",ws:"https://www.google.com/search?q=Grotta%20Palazzese%20ristorante",st:"Ristorante all interno di una grotta nella scogliera di Polignano a Mare. Una delle location piu fotografate al mondo. Cucina pugliese di mare con i ricci e il pesce dell Adriatico.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["La grotta nella scogliera di Polignano e la location piu fotografata dei ristoranti italiani.","Cenare letteralmente dentro la roccia sul mare e un esperienza che non ha eguali.","La cucina pugliese di mare e all altezza della location straordinaria."]},
  {n:"Il Bastione",a:"Via Castello 14, Monopoli, Puglia",pl:3,pr:"€€€ · ~60€",cu:"Pugliese di Mare",tg:"pesce",ws:"https://www.google.com/search?q=Il%20Bastione%20ristorante",st:"Ristorante all interno del castello di Monopoli, a picco sul mare Adriatico. Cucina pugliese di mare: polpo alla brace, orecchiette con le cozze, ricci al naturale.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["All interno del castello cinquecentesco a picco sul mare: una location che non si dimentica.","La cucina pugliese di mare qui e autentica: polpo, cozze e ricci del mare Adriatico.","Monopoli e uno dei borghi piu belli della Puglia: Il Bastione ne e il punto di riferimento."]},
  {n:"Il Beccafico",a:"Via Zara 1, Civitanova Marche, Marche",pl:2,pr:"€€ · ~40€",cu:"Pesce Adriatico",tg:"pesce",ws:"https://www.google.com/search?q=Il%20Beccafico%20ristorante",st:"Ristorante di pesce nel porto di Civitanova Marche. Cucina adriatica popolare: grigliate, fritture e crudi del giorno. Il pescato locale arriva direttamente dai pescherecci del porto.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Il pescato direttamente dai pescherecci del porto di Civitanova: freschezza assoluta garantita.","La cucina di mare adriatica qui e quella popolare e autentica: niente fronzoli, solo pesce.","Civitanova Marche ha un porto di pesca importante: il Beccafico ne e la miglior espressione gastronomica."]},
  {n:"Il Bergamotto",a:"Via Lungomare Italo Falcomatà 49, Reggio Calabria, Calabria",pl:3,pr:"€€€ · ~60€",cu:"Calabrese Contemporanea",tg:"italiana",ws:"https://www.google.com/search?q=Il%20Bergamotto%20ristorante",st:"Ristorante contemporaneo sul lungomare di Reggio Calabria. Cucina calabrese con il bergamotto, prodotto unico al mondo, come ingrediente protagonista: crostacei al bergamotto, tonno affumicato.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Il bergamotto di Reggio Calabria e un agrume unico al mondo: qui lo usano in cucina con maestria.","Il tonno affumicato al bergamotto e il piatto piu originale della cucina calabrese contemporanea.","Sul lungomare con la vista sull Etna e la Sicilia: la terrazza piu spettacolare della Calabria."]},
  {n:"Il Buco",a:"II Rampa Marina Piccola 5, Sorrento, Campania",pl:5,pr:"€€€€€ · ~130€",cu:"Alta Cucina Campana",tg:"italiana",ws:"https://www.google.com/search?q=Il%20Buco%20ristorante",st:"Una stella Michelin a Sorrento in un ex cantina medievale. Chef Giuseppe Aversa. Cucina campana contemporanea con ingredienti della penisola sorrentina: limoni sfusato, noci, pesce del golfo.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["In un ex cantina medievale del XIII secolo: l ambiente e uno dei piu suggestivi della Campania.","I limoni sfusato di Sorrento e le noci sono gli ingredienti piu identitari di questa cucina.","Chef Aversa porta Sorrento nel piatto con una cucina campana di grande finezza."]},
  {n:"Il Cantinone",a:"Via Fuorigrotta 12, Pozzuoli, Campania",pl:2,pr:"€€ · ~38€",cu:"Flegrea di Mare",tg:"pesce",ws:"https://www.google.com/search?q=Il%20Cantinone%20ristorante",st:"Osteria di mare a Pozzuoli nei Campi Flegrei. Cucina flegrea: zuppa di cozze di Baia, ricci, vongole veraci del golfo di Pozzuoli. Il pesce piu fresco e saporito della Campania.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Le cozze di Baia crescono nelle acque termali dei Campi Flegrei: sapore unico in Italia.","La zuppa di cozze flegrea e diversa da qualsiasi altra: il vulcanismo rende il sapore irripetibile.","Pozzuoli ha le acque piu ricche di fauna marina del Mediterraneo: il pesce e eccezionale."]},
  {n:"Il Clandestino",a:"Via Molo di Levante 1, Portonovo, Marche",pl:3,pr:"€€€ · ~60€",cu:"Pesce Adriatico",tg:"pesce",ws:"https://www.google.com/search?q=Il%20Clandestino%20ristorante",st:"Beach restaurant nella baia di Portonovo dello chef Moreno Cedroni. Cucina di mare informale con i moscioli, le orate e le grigliate sulla spiaggia. Il format estivo del grande chef marchigiano.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Moreno Cedroni porta la sua cucina in formato beach: informale ma di assoluta qualita.","I moscioli di Portonovo cucinati in ogni modo: la specialita della baia nella sua versione migliore.","Mangiare sulla spiaggia di Portonovo con lo chef piu famoso delle Marche: un privilegio."]},
  {n:"Il Duomo",a:"Via Capitano Bocchieri 31, Ragusa Ibla, Sicilia",pl:5,pr:"€€€€€ · ~170€",cu:"Alta Cucina Siciliana",tg:"italiana",ws:"https://www.google.com/search?q=Il%20Duomo%20ristorante",st:"Due stelle Michelin a Ragusa Ibla. Chef Ciccio Sultano. La cucina siciliana piu importante d Italia: Ragusano DOP, maiale nero dei Nebrodi, tonno di Mazzara. Un monumento gastronomico.",mi:{s:2,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:19,l:"19/20"},rv:["Due stelle Michelin a Ragusa Ibla: Ciccio Sultano e il piu grande chef siciliano.","La cucina siciliana di Sultano e una ricerca profonda sulle radici arabe, greche e normanne dell isola.","Il Ragusano DOP, il maiale nero dei Nebrodi e il tonno di Mazzara sono ingredienti di eccellenza mondiale."]},
  {n:"Il Fantasma",a:"Via Cavour 11, Alghero, Sardegna",pl:3,pr:"€€€ · ~60€",cu:"Algherese di Mare",tg:"pesce",ws:"https://www.google.com/search?q=Il%20Fantasma%20ristorante",st:"Ristorante di pesce storico di Alghero, la citta catalana di Sardegna. Cucina algherese di mare: l aragosta alla catalana, le arselle, il polpo di scoglio e il bottarga di muggine.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["L aragosta alla catalana di Alghero e uno dei piatti piu famosi della Sardegna.","Alghero e l unica citta catalana d Italia: la cucina ha influenze iberiche ancora riconoscibili.","Il mare davanti ad Alghero e tra i piu cristallini del Mediterraneo: il pesce e di qualita assoluta."]},
  {n:"Il Faro di Capo Spartivento",a:"Contrada Capo Spartivento, Brancaleone, Calabria",pl:4,pr:"€€€€ · ~80€",cu:"Ionica Calabrese",tg:"pesce",ws:"https://www.google.com/search?q=Il%20Faro%20di%20Capo%20Spartivento%20ristorante",st:"Ristorante all interno del faro storico di Capo Spartivento, il punto piu meridionale della Calabria. Cucina ionica: pesce spada, ricciola, delfino di mare. Vista sui due mari Ionio e Tirreno.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:14,l:"14/20"},rv:["All interno del faro storico di Capo Spartivento: l esperienza gastronomica piu unica della Calabria.","Il punto piu meridionale della Calabria dove si vedono due mari: Ionio e Tirreno insieme.","Il pesce ionio di queste acque e rarissimo: ricciole, dentici e cernie che non si trovano altrove."]},
  {n:"Il Frantoio di Ranzo",a:"Via Braie 1, Ranzo, Liguria",pl:3,pr:"€€€ · ~60€",cu:"Ligure Tradizionale",tg:"pesce",ws:"https://www.google.com/search?q=Il%20Frantoio%20di%20Ranzo%20ristorante",st:"Ristorante in un antico frantoio nella Liguria dell entroterra con vista sul mare. Cucina ligure autentica: pesce dell Imperia, erbe selvatiche, focaccia di Recco. Olio extravergine di produzione propria.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["L entroterra ligure con vista sul mare: una prospettiva rara e bellissima.","La cucina ligure delle erbe selvatiche, della focaccia e del pesce povero in versione autentica.","L olio extravergine di produzione propria e la base di ogni piatto: si sente."]},
  {n:"Il Gambero Rosso",a:"Via Mazzini 11, Cesenatico, Emilia Romagna",pl:3,pr:"€€€ · ~60€",cu:"Pesce Adriatico",tg:"pesce",ws:"https://www.google.com/search?q=Il%20Gambero%20Rosso%20ristorante",st:"Ristorante storico sul porto canale di Cesenatico. Cucina adriatica di tradizione: il fritto misto romagnolo, gli spaghetti allo scoglio e le seppie in zimino sono i piatti della casa.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Sul porto canale di Cesenatico: un indirizzo storico della cucina adriatica romagnola.","Il fritto misto romagnolo e quello della tradizione: leggero, croccante, con il pesce del giorno.","Un posto dove i romagnoli portano gli amici: la miglior garanzia di qualita."]},
  {n:"Il Pellicano",a:"Loc. Lo Sbarcatello, Porto Ercole, Toscana",pl:5,pr:"€€€€€ · ~180€",cu:"Alta Cucina Italiana",tg:"italiana",ws:"https://www.google.com/search?q=Il%20Pellicano%20ristorante",st:"Una stella Michelin all Hotel Il Pellicano a Porto Ercole sull Argentario. Cucina italiana d autore con terrazza sulla scogliera. Uno degli hotel piu esclusivi e romantici d Italia.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["L Hotel Il Pellicano e uno dei piu esclusivi d Italia: il ristorante e all altezza.","La terrazza sulla scogliera dell Argentario e una delle location piu romantiche del Mediterraneo.","Cucina italiana raffinata con ingredienti dell Argentario: il territorio nel piatto."]},
  {n:"Il Pontile",a:"Lungomare Scacciariello 15, Sperlonga, Lazio",pl:3,pr:"€€€ · ~60€",cu:"Pesce Laziale",tg:"pesce",ws:"https://www.google.com/search?q=Il%20Pontile%20ristorante",st:"Ristorante di pesce a Sperlonga, il borgo piu bello del Lazio. Vista sulla baia bianca con la Grotta di Tiberio sullo sfondo. Cucina di mare laziale autentica con pesce del Tirreno.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Sperlonga e il borgo piu bello del Lazio: cenare con la baia bianca come sfondo e magico.","La Grotta di Tiberio sullo sfondo e il pesce del Tirreno nel piatto: cucina e archeologia insieme.","Il Tirreno davanti a Sperlonga e cristallino: il pesce che si pesca qui e di una qualita rara."]},
  {n:"Il Porto",a:"Banchina San Nicola 14, Otranto, Puglia",pl:2,pr:"€€ · ~38€",cu:"Salentina di Mare",tg:"pesce",ws:"https://www.google.com/search?q=Il%20Porto%20ristorante",st:"Ristorante sul porto di Otranto, la porta d Oriente d Italia. Cucina salentina di mare con il pesce del Canale d Otranto: polpa di ricci, spaghetti alle cozze, frittura mista.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Otranto e la citta piu orientale d Italia: il mare del Canale ha pesci che non si trovano altrove.","La polpa di ricci di Otranto e tra le piu profumate del Mediterraneo.","Il porto di Otranto con la cattedrale e il castello: la location storica piu bella del Salento."]},
  {n:"Il Refettorio",a:"Via Bivio Conca 1, Conca dei Marini, Campania",pl:5,pr:"€€€€€ · ~130€",cu:"Alta Cucina Campana",tg:"pesce",ws:"https://www.google.com/search?q=Il%20Refettorio%20ristorante",st:"Una stella Michelin a Conca dei Marini sulla Costiera Amalfitana. All interno di un ex monastero medievale con terrazza sulla grotta dello Smeraldo. Cucina campana d autore.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["In un ex monastero medievale sulla Costiera Amalfitana: location impossibile da descrivere.","La grotta dello Smeraldo visibile dalla terrazza: si cena sul punto piu bello della Costiera.","Cucina campana d autore con gli agrumi e il pesce della Costiera Amalfitana."]},
  {n:"Il Romito",a:"Lungomare Rossini 9, Viareggio, Toscana",pl:3,pr:"€€€ · ~60€",cu:"Pesce Toscano",tg:"pesce",ws:"https://www.google.com/search?q=Il%20Romito%20ristorante",st:"Ristorante di pesce storico sul Lungomare di Viareggio. Cucina di mare versiliese: spaghetti alle telline, cacciucco livornese, branzino al sale. La cucina marinara della Versilia nella sua versione piu autentica.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Il cacciucco livornese di Il Romito e quello della tradizione: imperdibile a Viareggio.","Sul Lungomare di Viareggio con vista sul Tirreno: una location classica della Versilia.","Le telline di Viareggio con gli spaghetti sono il piatto simbolo della cucina marinara locale."]},
  {n:"Il Saraceno",a:"Via Lungomare 14, Sabaudia, Lazio",pl:3,pr:"€€€ · ~65€",cu:"Pesce Laziale",tg:"pesce",ws:"https://www.google.com/search?q=Il%20Saraceno%20ristorante",st:"Ristorante di pesce nel Parco Nazionale del Circeo a Sabaudia. Cucina laziale di mare con ingredienti del lago di Sabaudia e del Tirreno. Una location naturale di straordinaria bellezza.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Nel Parco Nazionale del Circeo: la natura come scenografia di una cena di pesce.","Il lago di Sabaudia e il Tirreno forniscono ingredienti di eccellenza che cambiano con la stagione.","Sabaudia e uno dei litorali piu belli del Lazio: Il Saraceno ne e l indirizzo gastronomico."]},
  {n:"Il Trabucco da Mimmo",a:"Via Borraco, Peschici, Puglia",pl:3,pr:"€€€ · ~65€",cu:"Garganica di Mare",tg:"pesce",ws:"https://www.google.com/search?q=Il%20Trabucco%20da%20Mimmo%20ristorante",st:"Ristorante sul trabucco storico di Peschici nel Gargano. Il trabucco e una macchina da pesca medievale a picco sul mare. Cucina del Gargano: alici fritte, lampuga, seppie dell Adriatico.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Il trabucco e una macchina da pesca medievale: cenare sopra uno di loro e un esperienza unica.","La cucina del Gargano e diversa dal resto della Puglia: pesce dell Adriatico piu selvaggio.","Le alici fritte del Gargano e la lampuga sono piatti che si trovano solo qui: autentica rarità."]},
  {n:"Il Veliero",a:"Via Marina 14, Scilla, Calabria",pl:3,pr:"€€€ · ~55€",cu:"Calabrese di Stretto",tg:"pesce",ws:"https://www.google.com/search?q=Il%20Veliero%20ristorante",st:"Ristorante sul lungomare di Scilla, il paese di Scylla della mitologia greca. Cucina dello Stretto: pesce spada, aguglie, alici di Bagnara. La spiaggia di Chianalea e la piu romantica della Calabria.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Scilla e il paese di Scylla della mitologia: cenare qui e un esperienza che unisce storia e sapori.","Il pesce dello Stretto di Messina e tra i piu pregiati d Italia: varietà uniche in queste acque.","La spiaggia di Chianalea sotto il castello aragonese e la location piu romantica della Calabria."]},
  {n:"Il Vistamare",a:"Via Lungomare di Ponente, Terracina, Lazio",pl:3,pr:"€€€ · ~60€",cu:"Pesce Laziale",tg:"pesce",ws:"https://www.google.com/search?q=Il%20Vistamare%20ristorante",st:"Ristorante di pesce con terrazza sul mare a Terracina. Cucina laziale di mare: linguine alle vongole di Terracina, spigola del Tirreno, fritto di paranza. Vista sul promontorio di Terracina.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["La terrazza su Terracina con vista sul promontorio e la baia e bellissima al tramonto.","Le vongole di Terracina sono le piu pregiate del Lazio: le linguine qui sono perfette.","Cucina laziale di mare autentica lontana da Roma: qualita e freschezza senza il conto della Capitale."]},
  {n:"L'Accademia",a:"Via Lungomare Falcomatà 11, Reggio Calabria, Calabria",pl:3,pr:"€€€ · ~55€",cu:"Calabrese di Mare",tg:"pesce",ws:"https://www.google.com/search?q=L'Accademia%20ristorante",st:"Ristorante di pesce sul lungomare Falcomatà, il chilometro piu bello d Italia secondo D Annunzio. Cucina calabrese di mare: pesce spada dello Stretto, spatola, alici di Bagnara.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Il lungomare Falcomatà e il chilometro piu bello d Italia: la vista sullo Stretto e l Etna e unica.","Il pesce spada dello Stretto di Messina e il prodotto gastronomico piu importante della Calabria.","La spatola e le alici di Bagnara Calabra sono prodotti rarissimi che si trovano solo qui."]},
  {n:"L'Ancora",a:"Via Roma 35, Villasimius, Sardegna",pl:2,pr:"€€ · ~42€",cu:"Sarda di Mare",tg:"pesce",ws:"https://www.google.com/search?q=L'Ancora%20ristorante",st:"Ristorante di pesce nel porto di Villasimius, nel parco naturale regionale del Capo Carbonara. Cucina sarda di mare: aragosta, bottarga, arselle e crostacei del Capo Carbonara.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Villasimius e nel parco naturale del Capo Carbonara: le acque sono tra le piu protette della Sardegna.","La bottarga di Villasimius e la bottarga dell arsella sono prodotti locali rarissimi.","Il porto di Villasimius e circondato dalle spiagge piu belle del Sud Sardegna."]},
  {n:"L'Osteria del Portuale",a:"Via Santa Chiara 19, Bari, Puglia",pl:2,pr:"€€ · ~38€",cu:"Barese Tradizionale",tg:"pesce",ws:"https://www.google.com/search?q=L'Osteria%20del%20Portuale%20ristorante",st:"Osteria barese autentica vicino al porto. Cucina pugliese di tradizione: spaghetti alle cozze di Taranto, tiella di riso patate e cozze, ricci crudi. I prodotti del mare Adriatico senza intermediari.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Le cozze di Taranto sono le migliori del Mediterraneo: qui le cucinano come si deve.","La tiella barese con riso, patate e cozze e il piatto piu identitario della cucina di Bari.","I ricci crudi del mare di Bari consumati vicino al porto: un rito gastronomico imprescindibile."]},
  {n:"La Caravella",a:"Via Matteo Camera 12, Amalfi, Campania",pl:5,pr:"€€€€€ · ~140€",cu:"Alta Cucina Amalfitana",tg:"pesce",ws:"https://www.google.com/search?q=La%20Caravella%20ristorante",st:"Una stella Michelin ad Amalfi. Dal 1959 il ristorante piu storico della Costiera. Cucina amalfitana d autore: scialatielli ai frutti di mare, alici di Cetara, limoni sfusato. Cantina di 25000 bottiglie.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["Dal 1959 il ristorante piu storico di Amalfi: la cucina amalfitana nella sua versione di eccellenza.","Gli scialatielli ai frutti di mare e le alici di Cetara sono i piatti simbolo della Costiera.","La cantina da 25000 bottiglie include verticali di Taurasi e Greco di Tufo rarissimi."]},
  {n:"La Carbonara",a:"Via Campo de Fiori 23, Roma, Lazio",pl:3,pr:"€€€ · ~55€",cu:"Romana Tradizionale",tg:"italiana",ws:"https://www.google.com/search?q=La%20Carbonara%20ristorante",st:"Trattoria storica romana dal 1906 a Campo de Fiori. La cucina romana tradizionale nella sua versione piu autentica: carbonara, cacio e pepe, coda alla vaccinara.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Dal 1906 a Campo de Fiori: una delle trattorie romane piu storiche e autentiche della Capitale.","La carbonara qui e quella classica della tradizione: crema d uovo densa e guanciale croccante.","Campo de Fiori la sera e uno dei contesti piu belli di Roma per cenare."]},
  {n:"La Frasca",a:"Via Matteotti 34, Castrocaro Terme, Emilia Romagna",pl:5,pr:"€€€€€ · ~120€",cu:"Alta Cucina Italiana",tg:"italiana",ws:"https://www.google.com/search?q=La%20Frasca%20ristorante",st:"Una stella Michelin in Romagna. Chef Giovanna Guidetti. Cucina italiana di alta qualita con ingredienti romagnoli di eccellenza. A breve distanza dalla costa adriatica.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["Una stella Michelin in Romagna per una cucina che racconta il territorio con grande onesta.","Giovanna Guidetti porta una prospettiva femminile e originale sulla cucina romagnola.","Gli ingredienti della Romagna nobiliti dalla tecnica: un equilibrio difficile e riuscito."]},
  {n:"La Ghinghetta",a:"Via Nazionale 4, Santa Teresa Gallura, Sardegna",pl:2,pr:"€€ · ~40€",cu:"Galllurese di Mare",tg:"pesce",ws:"https://www.google.com/search?q=La%20Ghinghetta%20ristorante",st:"Trattoria di pesce storica a Santa Teresa Gallura, a due passi dalla Corsica. Cucina gallurese di mare: la zuppa gallurese, l aragosta, le arselle e il pesce dello Stretto di Bonifacio.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Santa Teresa Gallura e a pochi chilometri dalla Corsica: il mare dello Stretto di Bonifacio e straordinario.","La zuppa gallurese e un piatto unico in Italia: pane, brodo e formaggi della Gallura.","L aragosta dello Stretto di Bonifacio e tra le piu pregiate del Mediterraneo."]},
  {n:"La Madia",a:"Corso Filippo Re Capriata 22, Licata, Sicilia",pl:5,pr:"€€€€€ · ~150€",cu:"Alta Cucina Siciliana",tg:"italiana",ws:"https://www.google.com/search?q=La%20Madia%20ristorante",st:"Due stelle Michelin a Licata. Chef Pino Cuttaia. La cucina del Mediterraneo nella sua visione piu filosofica: il mare come identita, gli ingredienti siciliani come radici, la memoria come ingrediente.",mi:{s:2,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:19,l:"19/20"},rv:["Pino Cuttaia e uno dei filosofi della cucina italiana: ogni piatto e un racconto del Mediterraneo.","La ricciola con lo zabaione al marsala e il piatto piu citato: siciliano nella profondita.","Due stelle Michelin a Licata, citta sconosciuta ai turisti: la ricompensa per chi sa cercare."]},
  {n:"La Pineta",a:"Via dei Cavalleggeri Nord 27, Marina di Bibbona, Toscana",pl:5,pr:"€€€€€ · ~150€",cu:"Alta Cucina di Mare",tg:"pesce",ws:"https://www.google.com/search?q=La%20Pineta%20ristorante",st:"Una stella Michelin tra la pineta e il mare a Marina di Bibbona. Chef Luciano Zazzeri. Il ristorante di pesce piu iconico della Toscana: pescato freschissimo della costa etrusca, nessun compromesso.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:18,l:"18/20"},rv:["Il ristorante di pesce piu importante della Toscana: Luciano Zazzeri conosce ogni pescatore della costa.","La posizione tra la pineta e il mare e irripetibile: si mangia ascoltando le onde.","Nessun menu fisso: si cucina solo quello che arriva in mattinata dai pescatori."]},
  {n:"La Puritate",a:"Via Sant'Angelo 18, Gallipoli, Puglia",pl:2,pr:"€€ · ~42€",cu:"Salentina di Mare",tg:"pesce",ws:"https://www.google.com/search?q=La%20Puritate%20ristorante",st:"Ristorante storico del centro storico di Gallipoli. Cucina salentina di mare: ricci di mare del basso Adriatico, polpo, alici di Nardo. Una delle cucine di mare piu autentiche del Salento.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["I ricci del basso Adriatico di Gallipoli sono i piu pregiati d Italia: qui li trovi freschi.","Il centro storico di Gallipoli e una delle isole piu belle del Mediterraneo.","La cucina salentina di La Puritate e quella autentica: nessuna contaminazione, solo tradizione."]},
  {n:"La Torre",a:"Lungomare di Levante 20, Numana, Marche",pl:3,pr:"€€€ · ~65€",cu:"Pesce Adriatico",tg:"pesce",ws:"https://www.google.com/search?q=La%20Torre%20ristorante",st:"Ristorante storico della riviera marchigiana con terrazza panoramica sul golfo del Conero. Cucina di mare adriatica di ottimo livello: pesce fresco, cotture rispettose e tocco creativo.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["La terrazza panoramica sul golfo del Conero e da sola un motivo sufficiente per venire.","La cucina di mare adriatica qui e quella di qualita: pesce fresco cucinato con rispetto.","Numana e uno dei borghi piu belli delle Marche: La Torre ne e il ristorante di riferimento."]},
  {n:"La Trattoria Enrico Bartolini",a:"Viale Lungomare Andrea Doria 37, Castiglione della Pescaia, Toscana",pl:5,pr:"€€€€€ · ~120€",cu:"Alta Cucina Italiana",tg:"italiana",ws:"https://www.google.com/search?q=La%20Trattoria%20Enrico%20Bartolini%20ristorante",st:"Una stella Michelin a Castiglione della Pescaia. Enrico Bartolini porta la sua cucina sulla costa maremmana. Alta cucina italiana con ingredienti toscani di eccellenza e vista sul Golfo di Follonica.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["Enrico Bartolini sceglie la Maremma per il suo ristorante di mare: scelta che racconta un territorio.","Il Golfo di Follonica come sfondo: una delle viste piu suggestive della costa toscana.","Alta cucina toscana che non dimentica le radici: ingredienti della Maremma in ogni piatto."]},
  {n:"Langosteria Paraggi",a:"Via Paraggi a Mare 2, Santa Margherita Ligure, Liguria",pl:5,pr:"€€€€€ · ~160€",cu:"Alta Cucina di Mare",tg:"pesce",ws:"https://www.google.com/search?q=Langosteria%20Paraggi%20ristorante",st:"Il brand di pesce piu glamour di Milano apre sulla spiaggia privata di Paraggi, la baia piu bella della Liguria. Crudi, crostacei, champagne e vista sul Tigullio.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["La baia di Paraggi e probabilmente la piu bella d Italia: Langosteria ne e l indirizzo perfetto.","Crudi di mare, ostriche e champagne sulla spiaggia piu esclusiva della Liguria.","Il salto da Milano al mare: la formula Langosteria funziona ancora meglio con il sole e l acqua."]},
  {n:"Le Cupole",a:"Lungomare Vittorio Veneto 6, Rapallo, Liguria",pl:4,pr:"€€€€ · ~85€",cu:"Italiana Contemporanea",tg:"pesce",ws:"https://www.google.com/search?q=Le%20Cupole%20ristorante",st:"Nella guida Michelin a Rapallo. Terrazza panoramica su mare e costa con vista fino a Portofino. Cucina italiana contemporanea con ingredienti liguri selezionati.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["La terrazza panoramica su Portofino e il Tigullio e tra le viste piu belle del levante ligure.","Cucina italiana contemporanea in una location che da sola vale tutto il viaggio.","La cupola panoramica permette di godere del panorama anche nelle serate ventose."]},
  {n:"Le Lumie",a:"Via E. Amari 32, Mazara del Vallo, Sicilia",pl:3,pr:"€€€ · ~60€",cu:"Mazarese di Mare",tg:"pesce",ws:"https://www.google.com/search?q=Le%20Lumie%20ristorante",st:"Ristorante di pesce a Mazara del Vallo, il porto di pesca piu importante del Mediterraneo. Cucina di mare mazarese: gambero rosso, tonno, pesce spada e cous cous di pesce alla trapanese.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Mazara del Vallo e il porto di pesca piu importante del Mediterraneo: il pesce e di qualita assoluta.","Il cous cous di pesce alla trapanese con il gambero rosso di Mazara e un capolavoro.","Il gambero rosso di Mazara e il piu pregiato d Italia: qui e freschissimo e a prezzo accessibile."]},
  {n:"Lo Scoglio",a:"Lungomare di Levante 40, Anzio, Lazio",pl:2,pr:"€€ · ~45€",cu:"Pesce Laziale",tg:"pesce",ws:"https://www.google.com/search?q=Lo%20Scoglio%20ristorante",st:"Ristorante di pesce ad Anzio, porto di pesca storico del Lazio. Cucina di mare con i gamberoni di Anzio, le triglie e il fritto di paranza. Il porto di Anzio e tra i piu importanti del Tirreno.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["I gamberoni di Anzio sono i piu pregiati del Tirreno: qui li cucinano nel modo migliore.","Il porto di Anzio e tra i piu importanti del Lazio: il pesce che arriva e di prima qualita.","Sul lungomare di Anzio con vista sul porto: la cucina di mare laziale nella sua versione autentica."]},
  {n:"Locanda Balestra",a:"Via Roma 15, Carloforte, Sardegna",pl:3,pr:"€€€ · ~65€",cu:"Tabarchina",tg:"pesce",ws:"https://www.google.com/search?q=Locanda%20Balestra%20ristorante",st:"Ristorante sull isola di San Pietro a Carloforte. Cucina tabarchina: il tonno rosso di Carloforte, il cascà, il pesto tabarchino. Una delle cucine piu rare e interessanti del Mediterraneo.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["La cucina tabarchina e una delle piu rare d Italia: influenze liguri, tunisine e sarde in un unico piatto.","Il tonno rosso di Carloforte e il prodotto gastronomico piu pregiato dell isola di San Pietro.","L isola di San Pietro e raggiungibile solo via traghetto: un isolamento che preserva l autenticita."]},
  {n:"Lorenzo",a:"Via Carducci 61, Forte dei Marmi, Toscana",pl:5,pr:"€€€€€ · ~160€",cu:"Alta Cucina di Mare",tg:"pesce",ws:"https://www.google.com/search?q=Lorenzo%20ristorante",st:"Una stella Michelin a Forte dei Marmi dal 1976. Chef Lorenzo Viani. Il ristorante di pesce storico della Versilia. Prodotti del Tirreno, crudi di eccellenza, servizio impeccabile.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["Dal 1976 il punto di riferimento della ristorazione di mare in Versilia.","I crudi di mare di Lorenzo sono leggendari: materia prima di assoluta eccellenza.","Il servizio impeccabile e la cantina straordinaria completano una delle migliori esperienze di mare in Italia."]},
  {n:"Madonnina del Pescatore",a:"Via Lungmare Italia 11, Senigallia, Marche",pl:5,pr:"€€€€€ · ~160€",cu:"Alta Cucina Adriatica",tg:"pesce",ws:"https://www.google.com/search?q=Madonnina%20del%20Pescatore%20ristorante",st:"Due stelle Michelin a Senigallia. Chef Moreno Cedroni. La cucina adriatica piu alta d Italia: ogni piatto e una ricerca profonda sul Mediterraneo e il Mar Adriatico.",mi:{s:2,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:19,l:"19/20"},rv:["Due stelle Michelin e la cucina adriatica piu importante d Italia: Cedroni e un maestro assoluto.","Ogni piatto e uno studio del mare: Cedroni conosce il Mediterraneo come pochi chef al mondo.","Senigallia diventa citta gastronomica grazie a Cedroni: vale il viaggio da qualsiasi parte d Italia."]},
  {n:"Mare Nostrum",a:"Lungomare Spadazzi 76, Cesenatico, Emilia Romagna",pl:3,pr:"€€€ · ~65€",cu:"Pesce Adriatico",tg:"pesce",ws:"https://www.google.com/search?q=Mare%20Nostrum%20ristorante",st:"Ristorante di pesce sul porto canale di Cesenatico, il paese di Pellegrino Artusi. Cucina adriatica della tradizione: brodetto alla cesenate, spaghetti alle vongole, anguilla marinata.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Il porto canale di Cesenatico e il piu bello della Romagna: il ristorante vi si affaccia direttamente.","Il brodetto cesenate e il piatto simbolo della cucina di mare romagnola: qui e quello autentico.","Cesenatico e il paese di Artusi: il rispetto per la cucina tradizionale e nel DNA del posto."]},
  {n:"Nido del Corvo",a:"Contrada Palazzi, Capo Vaticano, Calabria",pl:3,pr:"€€€ · ~60€",cu:"Calabrese di Mare",tg:"pesce",ws:"https://www.google.com/search?q=Nido%20del%20Corvo%20ristorante",st:"Ristorante a picco sulle scogliere di Capo Vaticano. La vista sul mare turchese e uno dei panorami piu spettacolari della Calabria. Cucina di mare locale: tonno, pesce spada e cernia.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["A picco sulle scogliere di Capo Vaticano: la vista sul Tirreno turchese e tra le piu belle d Italia.","Il mare di Capo Vaticano e tra i piu cristallini del Mediterraneo: il pesce e di qualita eccezionale.","Un ristorante dove la natura e protagonista assoluta: cucina e paesaggio in perfetto equilibrio."]},
  {n:"Nostrano",a:"Via Cavour 16, Pesaro, Marche",pl:4,pr:"€€€€ · ~90€",cu:"Alta Cucina Marchigiana",tg:"pesce",ws:"https://www.google.com/search?q=Nostrano%20ristorante",st:"Chef Stefano Ciotti. Cucina marchigiana contemporanea a Pesaro con forte radici marine adriatiche. Ingredienti del territorio: vincigrassi, brodetto, moscardini.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["Stefano Ciotti racconta le Marche con una cucina contemporanea che non dimentica le radici.","Il brodetto pesarese e il vincigrassi nelle versioni piu raffinate che si possano trovare.","Pesaro citta della musica (Rossini) e anche citta della buona cucina: Nostrano lo dimostra."]},
  {n:"Osteria dei Vespri",a:"Piazza Croce dei Vespri 6, Palermo, Sicilia",pl:4,pr:"€€€€ · ~90€",cu:"Alta Cucina Palermitana",tg:"italiana",ws:"https://www.google.com/search?q=Osteria%20dei%20Vespri%20ristorante",st:"Una stella Michelin in un palazzo nobiliare del 700 di Palermo. Chef Andrea Graziano. Cucina palermitana contemporanea: caponata, arancine, pasta con le sarde rivisitate con tecnica moderna.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["Un palazzo nobiliare del 700 a Palermo: l ambiente e gia una ragione sufficiente per venire.","La caponata e la pasta con le sarde di Andrea Graziano sono le versioni gourmet di piatti popolari.","Una stella Michelin nel cuore di Palermo per una cucina che racconta la Sicilia con intelligenza."]},
  {n:"Osteria dell'Aquila",a:"Via Oberdan 43, Cervia, Emilia Romagna",pl:2,pr:"€€ · ~38€",cu:"Romagnola Tradizionale",tg:"pesce",ws:"https://www.google.com/search?q=Osteria%20dell'Aquila%20ristorante",st:"Osteria tradizionale a Cervia, la citta del sale. Cucina romagnola di mare autentica: brodetto, spaghetti alle vongole locali, piadina fritta. Il sale di Cervia arricchisce ogni piatto.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Cervia e la citta del sale dolce piu pregiato d Italia: ogni piatto beneficia di questo ingrediente.","Il brodetto romagnolo con il sale di Cervia e uno dei piatti piu buoni della costa adriatica.","Un osteria autentica in una delle localita balneari piu belle della Romagna."]},
  {n:"Osteria la Sangiovesa",a:"Via delle Felci 7, Savignano sul Rubicone, Emilia Romagna",pl:2,pr:"€€ · ~35€",cu:"Romagnola Tradizionale",tg:"italiana",ws:"https://www.google.com/search?q=Osteria%20la%20Sangiovesa%20ristorante",st:"Osteria romagnola autentica vicino alla costa. Cucina della tradizione: piadina, cappelletti in brodo, squacquerone, Sangiovese di Romagna. Il genius loci della cucina romagnola.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["La cucina romagnola della tradizione in un osteria autentica vicino al mare.","La piadina con lo squacquerone e il prosciutto di Parma e un rito gastronomico imprescindibile.","Il Sangiovese di Romagna in caraffa accompagna una cucina senza compromessi."]},
  {n:"Pascucci al Porticciolo",a:"Via Fiumara 2, Fiumicino, Lazio",pl:4,pr:"€€€€ · ~100€",cu:"Alta Cucina di Mare",tg:"pesce",ws:"https://www.google.com/search?q=Pascucci%20al%20Porticciolo%20ristorante",st:"Una stella Michelin a Fiumicino. Chef Gianfranco Pascucci. Il miglior ristorante di pesce dell area romana: cucina del mare con tecnica sopraffina e ingredienti del Tirreno selezionati.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["Il miglior pesce dell area romana: Pascucci conosce ogni pescatore del Tirreno.","La zuppa di pesci e crostacei e un patrimonio immateriale della cucina laziale.","Vale il viaggio fino a Fiumicino: uno dei migliori ristoranti di pesce d Italia."]},
  {n:"Pasha",a:"Contrada Losciale, Polignano a Mare, Puglia",pl:5,pr:"€€€€€ · ~160€",cu:"Alta Cucina Pugliese",tg:"pesce",ws:"https://www.google.com/search?q=Pasha%20ristorante",st:"Due stelle Michelin e Tre Forchette Gambero Rosso 2026 a Polignano a Mare. Chef Antonello Magistà. Cucina pugliese d autore in una masseria con vista sul mare di Polignano.",mi:{s:2,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:18,l:"18/20"},rv:["Due stelle Michelin a Polignano: Magistà porta la cucina pugliese a livelli internazionali.","Il riccio di mare con la burrata e il piatto che racconta meglio la Puglia gastronomica.","La masseria con vista sul blu di Polignano e una delle location piu belle del Meridione."]},
  {n:"Principe Cerami",a:"Via Roma 45, Taormina, Sicilia",pl:5,pr:"€€€€€ · ~200€",cu:"Alta Cucina Siciliana",tg:"italiana",ws:"https://www.google.com/search?q=Principe%20Cerami%20ristorante",st:"Due stelle Michelin all Hotel San Domenico Palace di Taormina, uno dei quattro stagioni. Chef Massimo Mantarro. Vista sull Etna e il mare di Taormina. La cucina siciliana di eccellenza assoluta.",mi:{s:2,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:18,l:"18/20"},rv:["Due stelle Michelin con vista sull Etna e la baia di Taormina: la location piu iconica della Sicilia.","Massimo Mantarro porta la cucina siciliana a livelli di eccellenza internazionale.","L Hotel San Domenico Palace e uno dei piu leggendari d Italia: il ristorante e all altezza."]},
  {n:"Pura Vida Beach",a:"Viale Lungomare Colombo 22, Riccione, Emilia Romagna",pl:3,pr:"€€€ · ~55€",cu:"Cucina Fusion di Mare",tg:"pesce",ws:"https://www.google.com/search?q=Pura%20Vida%20Beach%20ristorante",st:"Beach restaurant contemporaneo a Riccione. Cucina fusion di mare con ingredienti adriatici e influenze internazionali. Aperitivo, cena e musica dal vivo sulla spiaggia piu glamour della Riviera.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["La Riviera Adriatica ha trovato il suo ristorante da spiaggia glamour: Pura Vida e quello.","Il menu fusion con ingredienti adriatici funziona meglio di quanto ci si aspetti.","Musica, aperitivo e cena sulla spiaggia di Riccione: l esperienza piu completa della Riviera."]},
  {n:"Qafiz",a:"Via Torretta 19, Santa Cristina d'Aspromonte, Calabria",pl:5,pr:"€€€€€ · ~120€",cu:"Alta Cucina Calabrese",tg:"italiana",ws:"https://www.google.com/search?q=Qafiz%20ristorante",st:"Una stella Michelin in Aspromonte. Chef Nino Rossi. Cucina calabrese di montagna e di mare in uno dei ristoranti piu sorprendenti del Sud Italia. A pochi minuti dal mare dello Stretto di Messina.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:17,l:"17/20"},rv:["Una stella Michelin in Aspromonte: la scoperta piu sorprendente della cucina del Sud Italia.","Nino Rossi racconta la Calabria con una cucina che non ha precedenti in regione.","A pochi minuti dal mare dello Stretto: terra e mare della Calabria in un unico percorso."]},
  {n:"Quattro Sorelle",a:"Via Lungomare di Levante 8, Gaeta, Lazio",pl:2,pr:"€€ · ~40€",cu:"Pesce Laziale",tg:"pesce",ws:"https://www.google.com/search?q=Quattro%20Sorelle%20ristorante",st:"Ristorante di pesce sul porto di Gaeta, tra i borghi marinari piu belli del Lazio. Cucina di mare laziale della tradizione: tiella di Gaeta, alici marinate, linguine alle vongole.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["La tiella di Gaeta e il piatto piu originale della cucina di mare laziale: non si trova altrove.","Gaeta e uno dei borghi marinari piu belli del Lazio: il porto e magnifico.","Le alici marinate del Golfo di Gaeta sono un prodotto di nicchia di straordinaria qualita."]},
  {n:"Quattro Trattoria Moderna",a:"Via Laguna 3, Marsala, Sicilia",pl:3,pr:"€€€ · ~60€",cu:"Siciliana Contemporanea",tg:"italiana",ws:"https://www.google.com/search?q=Quattro%20Trattoria%20Moderna%20ristorante",st:"Trattoria contemporanea a Marsala con vista sulle Isole Egadi. Cucina siciliana rivisitata: tonno rosso di Favignana, gambero rosso di Mazzara, pane cunzato. Il mare trapanese nel piatto.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["La vista sulle Isole Egadi al tramonto e una delle piu belle del Mediterraneo.","Il tonno rosso di Favignana e i gamberi di Mazzara del Vallo sono tra i migliori d Italia.","La cucina siciliana contemporanea qui trova un indirizzo di qualita in una citta del vino."]},
  {n:"Quintessenza",a:"Via Nazario Sauro 4, Trani, Puglia",pl:4,pr:"€€€€ · ~100€",cu:"Alta Cucina Pugliese",tg:"italiana",ws:"https://www.google.com/search?q=Quintessenza%20ristorante",st:"Chef Stefano Di Gennaro. Cucina pugliese contemporanea a Trani con ingredienti della Murgia e del mare Adriatico. Una delle tavole emergenti piu interessanti del Sud Italia.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Una delle cucine piu interessanti del Sud Italia: Trani sta diventando un polo gastronomico.","Di Gennaro usa gli ingredienti della Murgia e del mare in abbinamenti sorprendenti.","La Puglia contemporanea nel piatto: olio, mandorle e pesce dell Adriatico."]},
  {n:"Rezzano Cucina e Vino",a:"Via XXV Aprile 197, Sestri Levante, Liguria",pl:4,pr:"€€€€ · ~90€",cu:"Alta Cucina Ligure",tg:"pesce",ws:"https://www.google.com/search?q=Rezzano%20Cucina%20e%20Vino%20ristorante",st:"Nuova stella Michelin 2026 a Sestri Levante. Chef Guia Malteno e Simone Contiero. Cucina ligure contemporanea in un ristorante intimo nel centro storico, a pochi passi dal mare.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["Una delle stelle piu sorprendenti del 2026: cucina ligure autentica con grande tecnica.","Il pescato del Tigullio lavorato con rispetto e fantasia: ogni piatto e una sorpresa.","Sestri Levante non era sulla mappa gourmet: Rezzano la cambia definitivamente."]},
  {n:"Ristorante da Luciano",a:"Via Lungomare 32, Tropea, Calabria",pl:2,pr:"€€ · ~40€",cu:"Calabrese di Mare",tg:"pesce",ws:"https://www.google.com/search?q=Ristorante%20da%20Luciano%20ristorante",st:"Ristorante di pesce a Tropea, la perla del Tirreno calabrese. Cucina calabrese di mare con la cipolla rossa di Tropea: tonno con cipolla, filetti di spigola, frittura dello Stretto.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Tropea e la spiaggia piu bella della Calabria: il ristorante si trova nel posto giusto.","La cipolla rossa di Tropea IGP entra in ogni piatto: un ingrediente straordinario.","Il tonno con la cipolla rossa di Tropea e un abbinamento che non si dimentica."]},
  {n:"Ristorante del Gesuitello",a:"Via della Lunetta 6, Noto, Sicilia",pl:3,pr:"€€€ · ~60€",cu:"Siciliana Tradizionale",tg:"italiana",ws:"https://www.google.com/search?q=Ristorante%20del%20Gesuitello%20ristorante",st:"Ristorante barocco nel cuore di Noto, la citta del tardo barocco UNESCO. Cucina siciliana autentica con il pesce dello Ionio e gli agrumi di Avola: granita al limone di Avola, mandorle, pomodori datterini.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Noto e la citta del tardo barocco siciliano: la cucina nel palazzo nobiliare e un esperienza totale.","Le mandorle di Avola e i limoni di Noto sono tra gli agrumi piu pregiati del Mediterraneo.","Il pesce dello Ionio di Noto e poco conosciuto ma di eccellente qualita."]},
  {n:"Ristorante Il Funghetto",a:"Via Lago di Bolsena 4, Bolsena, Lazio",pl:2,pr:"€€ · ~35€",cu:"Pesce di Lago",tg:"pesce",ws:"https://www.google.com/search?q=Ristorante%20Il%20Funghetto%20ristorante",st:"Trattoria storica sul lago di Bolsena. Cucina dei coregoni, lucci e anguille del lago vulcanico piu grande d Europa. Una cucina di lago rarissima e preziosa nella tradizione laziale.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Il lago di Bolsena e il lago vulcanico piu grande d Europa: la cucina di lago qui e autentica.","I coregoni e le anguille del lago sono rarissimi in Italia: un patrimonio culinario da preservare.","Bolsena e il borgo piu bello del lago omonimo: Il Funghetto e la trattoria di riferimento."]},
  {n:"Ristorante La Lucciola",a:"Via Lungomare Mameli 10, Fano, Marche",pl:3,pr:"€€€ · ~55€",cu:"Pesce Adriatico",tg:"pesce",ws:"https://www.google.com/search?q=Ristorante%20La%20Lucciola%20ristorante",st:"Ristorante di pesce sul lungomare di Fano. Cucina adriatica di qualita: frittura mista, spaghetti con le vongole locali e il brodetto fanesco. Il porto di Fano porta il pesce piu fresco della mattina.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Il porto di Fano e tra i piu importanti dell Adriatico: il pesce che arriva e freschissimo.","Il brodetto fanesco e diverso da tutti gli altri: questa e la cucina di mare piu autentica delle Marche.","Sul lungomare con vista sul mare: una terrazza piacevole per pranzare dopo la spiaggia."]},
  {n:"Ristorante Li Lioni",a:"Loc. Li Lioni, Arzachena, Sardegna",pl:4,pr:"€€€€ · ~80€",cu:"Sarda di Mare",tg:"pesce",ws:"https://www.google.com/search?q=Ristorante%20Li%20Lioni%20ristorante",st:"Ristorante a pochi passi dalla Costa Smeralda. Cucina sarda di mare con pesce fresco della Gallura: aragoste, ostriche e dentici del Mar Tirreno. Terrazza con vista sulle Isole del Nord Sardegna.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["A pochi passi dalla Costa Smeralda: la qualita del pesce e quella delle acque piu pulite del Tirreno.","L aragosta e le ostriche della Gallura sono prodotti di eccellenza assoluta.","La vista sulle isole del Nord Sardegna e quella classica della Costa Smeralda al suo meglio."]},
  {n:"Ristorante Lido",a:"Lungomare di Levante 10, Cattolica, Emilia Romagna",pl:2,pr:"€€ · ~40€",cu:"Pesce Adriatico",tg:"pesce",ws:"https://www.google.com/search?q=Ristorante%20Lido%20ristorante",st:"Ristorante di pesce storico sul lungomare di Cattolica. Cucina adriatica popolare: grigliate di pesce fresco, frittura mista, spaghetti allo scoglio. La classica osteria di mare romagnola.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Cattolica e il confine tra Romagna e Marche: la cucina adriatica qui e ancora popolare e autentica.","La grigliata di pesce fresco del giorno e la scelta giusta: semplice e buonissima.","Il lungomare di Cattolica la sera e una passeggiata che si conclude sempre qui."]},
  {n:"Ristorante Maremonti",a:"Piazza Vittoria 2, Maratea, Calabria",pl:3,pr:"€€€ · ~60€",cu:"Lucano di Mare",tg:"pesce",ws:"https://www.google.com/search?q=Ristorante%20Maremonti%20ristorante",st:"Ristorante a Maratea, il gioiello del Tirreno tra Campania e Calabria. Cucina di mare con pesce dello Ionio e del Tirreno: spigola, sarago, alici e aguglie di Maratea.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Maratea e il gioiello del Tirreno: una costa incontaminata tra la Campania e la Calabria.","La spigola e il sarago pescati nelle acque di Maratea sono prodotti di nicchia di grande qualita.","Un ristorante che racconta un territorio gastronomico ancora poco conosciuto al grande pubblico."]},
  {n:"Ristorante Miramare",a:"Via del Porto 15, La Maddalena, Sardegna",pl:3,pr:"€€€ · ~60€",cu:"Maddalenina di Mare",tg:"pesce",ws:"https://www.google.com/search?q=Ristorante%20Miramare%20ristorante",st:"Ristorante sull arcipelago della Maddalena, parco nazionale marino. Cucina di mare dell arcipelago: aragoste, ricci, polpo e branzino del Parco Nazionale. Il mare piu protetto e pulito d Italia.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Il Parco Nazionale della Maddalena ha le acque piu pulite d Italia: il pesce e immacolato.","L aragosta e i ricci dell arcipelago sono prodotti che beneficiano della protezione marina.","La Maddalena e raggiungibile via traghetto: l isolamento garantisce qualita e autenticita."]},
  {n:"Ristorante Re di Bastoni",a:"Piazza IV Novembre 16, Crotone, Calabria",pl:2,pr:"€€ · ~38€",cu:"Crotonese di Mare",tg:"pesce",ws:"https://www.google.com/search?q=Ristorante%20Re%20di%20Bastoni%20ristorante",st:"Ristorante di pesce nel centro di Crotone, la citta di Pitagora sul mare Ionio. Cucina crotonese di mare: la pitta mpigliata, il baccala crotonese e il capocollo di Calabria con il pesce.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Crotone e la citta di Pitagora e Annibale: la cucina crotonese ha una storia millenaria.","Il baccala crotonese e uno dei piatti regionali piu originali d Italia: lavorazione unica.","La pitta mpigliata con il pesce locale e la cucina di Crotone nella sua versione piu autentica."]},
  {n:"Ristorante Sa Cardiga e su Schironi",a:"SS 195 km 14, Capoterra, Sardegna",pl:3,pr:"€€€ · ~60€",cu:"Sarda di Mare",tg:"pesce",ws:"https://www.google.com/search?q=Ristorante%20Sa%20Cardiga%20e%20su%20Schironi%20ristorante",st:"Ristorante storico sardo vicino alla laguna di Santa Gilla. Cucina sarda di lago e di mare: la bottarga, le anguille, i cefali e le orate della laguna. Il territorio sardo nel piatto.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["La laguna di Santa Gilla e il piu grande stagno salmastro della Sardegna: pesce rarissimo.","La bottarga prodotta in loco con le muggini della laguna e un prodotto che non si trova altrove.","La cucina della laguna sarda e diversa da quella di mare: un mondo gastronomico a parte."]},
  {n:"Rossellinis",a:"Via S. Giovanni del Toro 28, Ravello, Campania",pl:5,pr:"€€€€€ · ~160€",cu:"Alta Cucina Campana",tg:"italiana",ws:"https://www.google.com/search?q=Rossellinis%20ristorante",st:"Una stella Michelin a Ravello. Chef Luca Marra. Terrazza panoramica sul Golfo di Salerno dal Palazzo Avino. La vista piu alta e spettacolare della Costiera Amalfitana.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["La terrazza di Ravello a 365 metri sul mare e la piu alta e spettacolare della Costiera.","Chef Marra costruisce una cucina campana di grande eleganza all altezza della location divina.","Ravello e la citta della musica e della bellezza: Rossellinis e il ristorante che la incarna meglio."]},
  {n:"Sciabola",a:"Via Arenile 1, Forte dei Marmi, Toscana",pl:4,pr:"€€€€ · ~90€",cu:"Alta Cucina di Mare",tg:"pesce",ws:"https://www.google.com/search?q=Sciabola%20ristorante",st:"Nuova stella Michelin 2026 a Forte dei Marmi. Chef Alessandro Ferrarini. Cucina di mare versiliese contemporanea con ingredienti del Tirreno. Una delle aperture piu interessanti del 2025.",mi:{s:1,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:15,l:"15/20"},rv:["Nuova stella Michelin 2026: Alessandro Ferrarini porta una cucina di mare originale a Forte dei Marmi.","Il Tirreno in tavola: ingredienti selezionati con cura e cucinati con tecnica contemporanea.","Forte dei Marmi diventa sempre piu un polo gastronomico: Sciabola ne e la conferma."]},
  {n:"Taverna del Capitano",a:"Piazza delle Sirene 10, Marina del Cantone, Campania",pl:5,pr:"€€€€€ · ~150€",cu:"Alta Cucina di Mare",tg:"pesce",ws:"https://www.google.com/search?q=Taverna%20del%20Capitano%20ristorante",st:"Una stella Michelin a Marina del Cantone nella penisola sorrentina. Chef Alfonso e Mariella Caputo. Cucina di mare campana di grande raffinatezza nella baia piu pittoresca del Cilento.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:17,l:"17/20"},rv:["Marina del Cantone e la baia piu pittoresca della penisola sorrentina: cenare qui e magico.","Alfonso Caputo porta la cucina di mare campana a livelli di grande raffinatezza tecnica.","Il pesce del golfo di Napoli in questa baia e di una qualita che non si trova altrove."]},
  {n:"Tonno di Corsa",a:"Via Roma 15, Carloforte, Sardegna",pl:2,pr:"€€ · ~45€",cu:"Tabarchina di Mare",tg:"pesce",ws:"https://www.google.com/search?q=Tonno%20di%20Corsa%20ristorante",st:"Ristorante dedicato al tonno rosso di Carloforte sull isola di San Pietro. Il tonno di corsa e quello della mattanza, la pesca tradizionale del tonno piu antica del Mediterraneo.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Il tonno di corsa e quello della mattanza tradizionale: la pesca piu antica del Mediterraneo.","Ogni parte del tonno viene usata: ventresca, bottarga, ficazza e buzzonaglia sono i prodotti della tradizione.","L isola di San Pietro custodisce una delle tradizioni gastronomiche piu rare d Italia."]},
  {n:"Torre del Saracino",a:"Via Marina d'Equa 1, Vico Equense, Campania",pl:5,pr:"€€€€€ · ~200€",cu:"Alta Cucina Campana",tg:"pesce",ws:"https://www.google.com/search?q=Torre%20del%20Saracino%20ristorante",st:"Due stelle Michelin a Vico Equense sulla penisola sorrentina. Chef Gennaro Esposito. Sospeso tra terra e mare con vista sul Golfo di Napoli. Uno dei templi della cucina italiana contemporanea.",mi:{s:2,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:19,l:"19/20"},rv:["Due stelle Michelin tra terra e mare: la vista sul Golfo di Napoli durante la cena e mozzafiato.","Gennaro Esposito e uno dei chef piu importanti d Italia: cucina campana di assoluta eccellenza.","La pasta con il pomodoro del Vesuvio e il piatto che racconta meglio questa cucina straordinaria."]},
  {n:"Uliassi",a:"Banchina di Levante 6, Senigallia, Marche",pl:5,pr:"€€€€€ · ~200€",cu:"Alta Cucina Adriatica",tg:"pesce",ws:"https://www.google.com/search?q=Uliassi%20ristorante",st:"Tre stelle Michelin a Senigallia sul porto. Chef Mauro Uliassi. Uno dei migliori ristoranti d Italia e del mondo. Cucina adriatica visionaria: il mare come metafora e come ingrediente.",mi:{s:3,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:20,l:"20/20"},rv:["Tre stelle Michelin sul porto di Senigallia: uno dei migliori ristoranti al mondo.","Mauro Uliassi ha creato una cucina adriatica che non ha precedenti nella storia della gastronomia italiana.","Il Mare Nordico, piatto simbolo di Uliassi, e un capolavoro: alghe, ricci, conchiglie e onde."]},
  {n:"Vignamare",a:"Strada Castello, Andora, Liguria",pl:3,pr:"€€€ · ~65€",cu:"Ligure Contemporanea",tg:"pesce",ws:"https://www.google.com/search?q=Vignamare%20ristorante",st:"Ristorante con vista panoramica sul mare costruito su una cisterna irrigua. Menu che cambia ogni giorno con orto proprio e pescato fresco. Vista sull orizzonte tra i vigneti.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Costruito su una vecchia cisterna irrigua tra i vigneti: una location impossibile da dimenticare.","Menu che cambia ogni giorno con quello che offre l orto e il mercato del pesce.","La vista sull orizzonte dal vigneto e una delle piu ampie della riviera di Ponente."]},
  {n:"Zass",a:"Via San Pietro 26, Positano, Campania",pl:5,pr:"€€€€€ · ~170€",cu:"Alta Cucina di Mare",tg:"pesce",ws:"https://www.google.com/search?q=Zass%20ristorante",st:"Una stella Michelin all Hotel Il San Pietro di Positano. La terrazza sul mare di Positano e una delle piu fotografate al mondo. Cucina italiana d autore con vista mozzafiato.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["La terrazza di Zass e probabilmente la piu fotografata dei ristoranti italiani: vista assoluta.","Il San Pietro di Positano e uno degli hotel piu iconici al mondo: il ristorante e all altezza.","Cucina italiana raffinata con gli ingredienti della Costiera: limoni, alici, pomodori del Vesuvio."]}
];
var favs=new Set(JSON.parse(localStorage.getItem('mafav25')||'[]'));
var wish=new Set(JSON.parse(localStorage.getItem('mawish25')||'[]'));
function saveFavs(){localStorage.setItem('mafav25',JSON.stringify(Array.from(favs)));}
function saveWish(){localStorage.setItem('mawish25',JSON.stringify(Array.from(wish)));}

window.toggleWish=function(i){
  var n=R[i].n;
  wish.has(n)?wish.delete(n):wish.add(n);
  saveWish();updateWishCount();render();
};

window.toggleFav=function(i){
  var n=R[i].n;
  favs.has(n)?favs.delete(n):favs.add(n);
  saveFavs();

updateFavCount();render();
};

var S={c:'all',p:'all',g:'all',z:'all',q:'',fav:false,wish:false};

var mainZones=['liguria','toscana','emilia romagna','marche','lazio','campania','puglia','calabria','sicilia','sardegna'];

function getZone(a){return a.split(',').pop().trim().toLowerCase();}

function maps(a){return'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(a+', Milano');}

function miBadge(r){
  if(r.mi.s>=1)return'<span class="sg mi">'+'\u2B50'.repeat(r.mi.s)+' '+(r.mi.s===1?'Una Stella':r.mi.s+' Stelle')+' <span class="gn">Michelin</span></span>';
  if(r.mi.b)return'<span class="sg mi">\uD83D\uDE0A Bib Gourmand <span class="gn">Michelin</span></span>';
  if(r.mi.g)return'<span class="sg mi" style="background:#f0fff4;border-color:#a8d5b5;color:#276749">\uD83C\uDF3F Green Star <span class="gn">Michelin</span></span>';
  return'<span class="sg mi fd">\u2B50 \u2013 <span class="gn">Michelin</span></span>';
}

function makeCard(r,i){
  var isFav=favs.has(r.n);
  var isWish=wish.has(r.n);
  var ta='https://www.tripadvisor.it/Search?q='+encodeURIComponent(r.n);
  var rvs='';
  for(var k=0;k<r.rv.length;k++)rvs+='<div class="rv"><span class="st">\u2605\u2605\u2605\u2605\u2605</span><span>'+r.rv[k]+'</span></div>';
  return '<div class="card">'
    +'<button class="favbtn'+(isFav?' on':'')+'" onclick="toggleFav('+i+')">'+( isFav?'\u2764\uFE0F':'\uD83E\uDD0D')+'</button>'
    +'<button class="wishbtn'+(isWish?' on':'')+'" onclick="toggleWish('+i+')">'+( isWish?'\u2705':'\u2714\uFE0F')+'</button>'
    +'<div class="cb">'
    +'<div class="ctag"><span class="ccu">'+r.cu.toUpperCase()+'</span><span class="cpr">'+r.pr+'</span></div>'
    +'<h2 class="cn"><a href="'+r.ws+'" target="_blank" style="color:inherit;text-decoration:none;">'+r.n+'</a></h2>'
    +'<div class="lks">'
    +'<a href="'+maps(r.a)+'" target="_blank">\uD83D\uDCCD '+r.a+'</a>'
    +'<a href="'+r.ws+'" target="_blank" class="ws">\uD83C\uDF10 Sito web</a>'
    +'<a href="'+ta+'" target="_blank" class="ta">\uD83C\uDF7D TripAdvisor</a>'
    +'</div>'
    +'<div class="sc">'+miBadge(r)
    +'<span class="sg gr">'+'\uD83C\uDF74'.repeat(r.gr.f)+' '+r.gr.l+' <span class="gn">Gambero Rosso</span></span>'
    +'<span class="sg es">\u2615 '+r.es.l+' <span class="gn">L\u2019Espresso</span></span>'
    +'</div>'
    +'<p class="cs">'+r.st+'</p>'
    +'<div class="rvs">'+rvs+'</div>'
    +'</div></div>';
}

function updateFavCount(){
  var n=favs.size;
  document.getElementById('favc').textContent=n>0?'('+n+')':'';
}
function updateWishCount(){
  var n=wish.size;
  document.getElementById('wishc').textContent=n>0?'('+n+')':'';
}

function render(){
  var f=[];
  for(var i=0;i<R.length;i++){
    var r=R[i];
    if(S.c!=='all'&&r.tg!==S.c)continue;
    if(S.p!=='all'&&r.pl!==parseInt(S.p))continue;
    if(S.g==='michelin'&&!r.mi.s&&!r.mi.b&&!r.mi.g)continue;
    if(S.g==='gambero'&&r.gr.f<2)continue;
    if(S.g==='espresso'&&r.es.v<15)continue;
    if(S.z!=='all'){var rz=getZone(r.a);if(S.z==='other'){if(mainZones.indexOf(rz)!==-1)continue;}else{if(rz!==S.z)continue;}}
    if(S.fav&&!favs.has(r.n))continue;
    if(S.wish&&!wish.has(r.n))continue;
    if(S.q){var q=S.q.toLowerCase();var ok=false;var ff=[r.n,r.cu,r.a,r.st];for(var j=0;j<ff.length;j++){if(ff[j].toLowerCase().indexOf(q)>=0){ok=true;break;}}if(!ok)continue;}
    f.push(i);
  }
  document.getElementById('tot').textContent=f.length;
  var rcEl=document.getElementById('rc');if(rcEl)rcEl.textContent=f.length+' risultati';
  var grid=document.getElementById('grid');
  var cards=grid.querySelectorAll('.card');
  for(var k=0;k<cards.length;k++)cards[k].remove();
  document.getElementById('nr').style.display=f.length?'none':'block';
  for(var m=0;m<f.length;m++)grid.insertAdjacentHTML('beforeend',makeCard(R[f[m]],f[m]));
}

document.getElementById('zg').addEventListener('click',function(e){var b=e.target.closest('.fb');if(!b)return;document.querySelectorAll('#zg .fb').forEach(function(x){x.classList.remove('on');});b.classList.add('on');S.z=b.dataset.z;render();});
document.getElementById('cg').addEventListener('click',function(e){var b=e.target.closest('.fb');if(!b)return;document.querySelectorAll('#cg .fb').forEach(function(x){x.classList.remove('on');});b.classList.add('on');S.c=b.dataset.c;render();});
document.getElementById('pg').addEventListener('click',function(e){var b=e.target.closest('.fb');if(!b)return;document.querySelectorAll('#pg .fb').forEach(function(x){x.classList.remove('on');});b.classList.add('on');S.p=b.dataset.p;render();});
document.getElementById('gg').addEventListener('click',function(e){var b=e.target.closest('.fb');if(!b)return;document.querySelectorAll('#gg .fb').forEach(function(x){x.classList.remove('on');});b.classList.add('on');S.g=b.dataset.g;render();});
document.getElementById('favf').addEventListener('click',function(){S.fav=!S.fav;S.wish=false;document.getElementById('wishf').classList.remove('on');this.classList.toggle('on',S.fav);render();});
document.getElementById('wishf').addEventListener('click',function(){S.wish=!S.wish;S.fav=false;document.getElementById('favf').classList.remove('on');this.classList.toggle('on',S.wish);render();});
document.getElementById('srch').addEventListener('input',function(e){S.q=e.target.value;render();});

updateFavCount();
updateWishCount();
render();
